### ISSUE TITLE
Record lock even when the content manager has left the page

### ISSUE THREAD

**Issue by NEONefffect** [notum-cz/strapi-plugin-record-locking#26]
Record lock even when the content manager has left the page ( go back, close tab/browser) 

steps to reproduce:
1 open any entry
2 close tab
3 open another browser/incognito window
4 login under another account
5 open the same record

Strapi Version: 4.10.2
Node/Yarn Version: yarn/1.22.11 npm/? node/v18.16.0 darwin x64
Edition: Community
Database: postgres
  "@notum-cz/strapi-plugin-record-locking": "^0.3.3"

**Comment by NEONefffect** [comment]
isusu with @strapi-community/strapi-plugin-url-alias 
added   "visible": false  solve problem
```js
  "pluginOptions": {
    "content-manager": {
      "visible": false,
    },
    "content-type-builder": {
      "visible": false,
    },
  },
```

**Comment by IgorNichiporuk** [comment]
@omikulcik Is this issue fixed in v1.3.8?

**Comment by IgorNichiporuk** [comment]
Hi, @omikulcik, sorry for late response!
There is my package.json (part of it):
"devDependencies": {
    "@strapi/eslint-config": "^0.1.2",
    "@types/node-fetch": "^2.6.4",
    "@types/pg": "^8.6.6",
    "@typescript-eslint/eslint-plugin": "^5.14.0",
    "@typescript-eslint/parser": "^5.14.0",
    "eslint": "8.22.0",
    "eslint-config-airbnb-typescript": "^16.1.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "typescript": "^4.6.2",
    "webpack": "^5.75.0"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@notum-cz/strapi-plugin-record-locking": "^1.3.8",
    "@strapi/plugin-documentation": "4.13.7",
    "@strapi/plugin-graphql": "4.13.7",
    "@strapi/plugin-i18n": "4.13.7",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.13.7",
    "@strapi/provider-upload-aws-s3": "^4.11.1",
    "@strapi/strapi": "4.13.7",
    "@types/lodash": "^4.14.191",
    "axios": "^1.4.0",
    "css-loader": "^6.7.3",
    "escape-html": "^1.0.3",
    "lodash": "^4.17.21",
    "mongodb": "^5.0.1",
    "node-fetch": "^3.3.1",
    "patch-package": "^8.0.0",
    "pg": "8.8.0",
    "pluralize": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "strapi-plugin-entity-relationship-chart": "^4.1.0",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-multi-select": "^1.1.0",
    "strapi-plugin-preview-button": "1.1.3",
    "strapi-plugin-redirects": "^0.0.6",
    "style-loader": "^3.3.2"
  },
  "overrides": {
    "strapi-plugin-redirects": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    }
  },
  
  And yes, yday I received again the message from the editor: 'We have a problem with Strapi again, it says that the page is edited by another editor but it is closed.'

**Comment by IgorNichiporuk** [comment]
<img width="729" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/60503041/722116fb-ff5c-4e49-8938-0c85a12ef2ef"> <img width="743" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/60503041/4dc5abe9-c3d3-41c5-a3b2-ff67d33ab25c">

Итак, я был на странице /about-us/, закрыл ее и остался на /albania/. Как видите, мы оба можем одновременно находиться на странице /albania/, но коллега не может перейти на страницу /about-us/.

Скриншоты из разговора с коллегой. Вот его экран, когда я был на странице /albania/.


Итак, я был на странице /about-us/, закрыл ее и остался на /albania/. Как видите, мы оба можем находиться на странице /albania/ одновременно, но коллега не может посетить страницу /about-us/.

Скриншоты из разговора с коллегой. Вот его экран, когда я находился на странице /albania/

**Comment by IgorNichiporuk** [comment]
And, funny enough, it works fine on localhost

**Comment by omikulcik** [comment]
I think it might be problem with transporters I have just merged #66 and will release a new version immediately. Please, check whether that fixes your issue.

**Comment by IgorNichiporuk** [comment]
Thanks a lot!
Unfortunately, after updating I got this:
<img width="1350" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/60503041/aac54bbd-57ac-44d5-8755-91c8dc7264ba">
<img width="651" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/60503041/e0594958-bdcf-4b0b-b413-49d84d316c49">

I haven't caught the reason, but with 1.3.8 Strapi worked

**Comment by IgorNichiporuk** [comment]
And what's interesting, I was trying 1.3.9; 1.3.8; 1.3.6 and always got the same error

I wanted to open one of the entities from my collection
<img width="1478" alt="image" src="https://github.com/notum-cz/strapi-plugin-record-locking/assets/60503041/a937c36d-cb85-4039-b8f4-7e9914c74f47">

**Comment by IgorNichiporuk** [comment]
@omikulcik, do you have any ideas?

**Comment by IgorNichiporuk** [comment]
@omikulcik, Hi!
The issue is still presented.

Editor's message:
"Hi, I'm experiencing the problem of not being able to get into an article in Strapi because it thinks someone else is editing the article when they're not. The problem started yesterday pm and it's the same this morning, Thank you! "

`"devDependencies": {
    "@strapi/eslint-config": "^0.1.2",
    "@types/node-fetch": "^2.6.4",
    "@types/pg": "^8.6.6",
    "@typescript-eslint/eslint-plugin": "^5.14.0",
    "@typescript-eslint/parser": "^5.14.0",
    "eslint": "8.22.0",
    "eslint-config-airbnb-typescript": "^16.1.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "typescript": "^4.6.2",
    "webpack": "^5.75.0"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@notum-cz/strapi-plugin-record-locking": "^1.3.10",
    "@strapi/plugin-documentation": "4.20.2",
    "@strapi/plugin-graphql": "4.20.2",
    "@strapi/plugin-i18n": "4.20.2",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.20.2",
    "@strapi/provider-upload-aws-s3": "^4.11.1",
    "@strapi/strapi": "4.20.2",
    "@types/lodash": "^4.14.191",
    "axios": "^1.4.0",
    "css-loader": "^6.7.3",
    "escape-html": "^1.0.3",
    "lodash": "^4.17.21",
    "mongodb": "^5.0.1",
    "node-fetch": "^3.3.1",
    "patch-package": "^8.0.0",
    "pg": "8.8.0",
    "pluralize": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "strapi-plugin-entity-relationship-chart": "^4.1.0",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-multi-select": "^1.1.0",
    "strapi-plugin-preview-button": "1.1.3",
    "strapi-plugin-redirects": "^0.0.6",
    "style-loader": "^3.3.2",
    "styled-components": "5.3.3"
  },`
  
I would be very much appreciative of any help
